from LinearRegressor import LinearRegressor
from LogisticRegressor import LogisticRegressor
from HypothesisTests import HypothesisTest1, HypothesisTest2
from Plotting import *
import os

#DO NOT EDIT THIS FILE

def Question1():
    HypothesisTest1()

def Question2():
    HypothesisTest2()

def Question3(trainfilename,testfilename):
    alpha = 0.05
    linr = LinearRegressor("liver_data", alpha, trainfilename, testfilename)
    lin_y_test_pred_err = linr.evaluateRegressor()
    return lin_y_test_pred_err

def Question4(trainfilename,testfilename):
    alpha = 0.05
    linr = LinearRegressor("wine_quality", alpha, trainfilename, testfilename)
    lin_y_test_pred_err = linr.evaluateRegressor()
    return lin_y_test_pred_err

def Question5(trainfilename,testfilename):
    alpha = 0.05
    logr = LogisticRegressor("wine_quality", alpha, trainfilename, testfilename)
    log_y_test_pred_err = logr.evaluateRegressor()
    return log_y_test_pred_err

def Question6(trainfilename):
    X, y = LinearRegressor.readData(trainfilename)
    visualizeGammaGlutamylHalfPintsScatterPlot(X,path=os.path.join("results","plots","GammaGlutamylHalfPintsScatterPlot.pdf"))
    visualizeAlanineATBoxPlot(X,path=os.path.join("results","plots","AlanineATBoxPlot.pdf"))
    visualizeMCVHistogram(X,path=os.path.join("results","plots","MCVHistogram.pdf"))

def Question7(lin_liver_y_test_pred_err,lin_wine_y_test_pred_err,log_wine_y_test_pred_err):
    liverDataPredictionErrorHistogram(lin_liver_y_test_pred_err)
    linearAndLogisticRegressionErrorComparison(lin_wine_y_test_pred_err,log_wine_y_test_pred_err)

if __name__ == '__main__':

    #10 points: Hypothesis Test Question 1 in HypothesisTests.py
    Question1()

    #10points: Hypothesis Test Question 2A,2B in HypothesisTests.py
    Question2()

    liver_trainfilename = os.path.join("data","liver_data_train.csv")
    liver_testfilename = os.path.join("data","liver_data_test.csv")
    wine_trainfilename = os.path.join("data", "wine_quality_train.csv")
    wine_testfilename = os.path.join("data", "wine_quality_test.csv")

    #20 points: Linear Regression on Liver Data
    lin_liver_y_test_pred_err=Question3(liver_trainfilename,liver_testfilename)

    #20 points: Linear Regression on Wine Data
    lin_wine_y_test_pred_err=Question4(wine_trainfilename,wine_testfilename)

    #10 points: Logistic Regression on Wine Data
    log_wine_y_test_pred_err = Question5(wine_trainfilename,wine_testfilename)

    #10 points: Plotting attributes of Wine Data
    Question6(liver_trainfilename)

    #10 points: Plotting errors of liver and wine data predictions
    Question7(lin_liver_y_test_pred_err,lin_wine_y_test_pred_err,log_wine_y_test_pred_err)